import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image src="https://owa-lb-test.thenational.academy/images/illustrations/teacher-carrying-stuff-237-286.png" width={1920} height={300} alt="png"/>

        </main>
    </div>
  )
}
